apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
bases:
- ../../base

nameSuffix: -production

replicas:
- name: vault
  count: 5

patchesStrategicMerge:
- statefulset.yaml

commonLabels:
  environment: production

images:
  - name: oss-vault-audit # match images with this name
    newTag: dev # override the tag
    newName: us-west1-docker.pkg.dev/myproject/myteam/oss-vault-audit # override the name