apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- server-clusterrolebinding.yaml
- server-config-configmap.yaml
- server-service.yaml
- server-statefulset.yaml
- audit-configmap.yaml

commonLabels:
  app: vault
  component: server