apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
bases:
- ../../base

commonLabels:
  environment: dev

images:
  - name: oss-vault-audit # match images with this name
    newTag: dev # override the tag
    newName: us-west1-docker.pkg.dev/myproject/myteam/oss-vault-audit # override the name